RESOURCE_OPERATIONS = {
    'account': {'read': [()]},
    'campaign': {'create': [()], 'query': [()], 'read': [()], 'update': [()]},
    'customField': {
        'create': [()],
        'delete': [()],
        'query': [()],
        'read': [()],
        'update': [()],
    },
    'customRedirect': {'query': [()], 'read': [()]},
    'dynamicContent': {'query': [()], 'read': [()]},
    'email': {'read': [()], 'send': [(), (), ()], 'stats': [()]},
    'emailClick': {'query': [()]},
    'emailTemplate': {'listOneToOne': [()], 'read': [()]},
    'form': {'query': [()], 'read': [()]},
    'lifecycleHistory': {'query': [()], 'read': [()]},
    'lifecycleStage': {'query': [()]},
    'list': {
        'create': [()],
        'delete': [()],
        'query': [()],
        'read': [()],
        'update': [()],
    },
    'listMembership': {
        'create': [()],
        'delete': [(), ()],
        'query': [()],
        'read': [(), ()],
        'update': [(), ()],
    },
    'opportunity': {'query': [()]},
    'opportunity ': {
        'create': [(), ()],
        'delete': [()],
        'read': [()],
        'undelete': [()],
        'update': [()],
    },
    'prospect': {'query': [()]},
    'prospect ': {
        'assign': [(), ()],
        'batchCreate': [()],
        'batchUpdate': [()],
        'batchUpsert': [()],
        'create': [()],
        'delete': [(), ()],
        'read': [(), ()],
        'unassign': [(), ()],
        'update': [(), ()],
        'upsert': [()],
    },
    'prospectAccount': {
        'assign': [()],
        'create': [()],
        'describe': [()],
        'query': [()],
        'read': [()],
        'update': [()],
    },
    'tag': {'query': [()], 'read': [()]},
    'tagObject': {'query': [()], 'read': [()]},
    'user': {'query': [()], 'read': [(), ()]},
    'visit': {'query': [()], 'read': [()]},
    'visitor': {'assign': [()], 'query': [()], 'read': [()]},
    'visitorActivity': {'query': [()], 'read': [()]},
}
